
const generateEmails = () => {
    const lastNames = [
        "Doe", "Smith", "Johnson", "Brown", "Lee", "Santos", "Mendez", "Dela Cruz",
        "Rivera", "Nichols", "Roxas", "Villar", "Dizon", "Uy", "Go", "Ombog",
        "Legaspi", "Samonte", "Serapio", "Fernandez", "Anderson", "Clark", "Evans",
        "Garcia", "Harris", "James", "Jones", "Kim", "Martinez", "Moore", "Nguyen",
        "Ortiz", "Parker", "Peterson", "Ramirez", "Roberts", "Scott", "Taylor",
        "Thomas", "Walker", "White", "Wright", "Young", "Zhang", "Adams", "Baker",
        "Campbell", "Davis", "Edwards", "Foster", 

        "Andrews", "Armstrong", "Bailey", "Bennett", "Brooks", "Bryant", "Butler", "Carroll", 
        "Chapman", "Collins", "Cooper", "Cox", "Curtis", "Daniels", "Dawson", "Diaz", 
        "Duncan", "Ellis", "Fisher", "Fleming", "Ford", "Freeman", "Gomez", "Gonzales", 
        "Graham", "Grant", "Griffin", "Gutierrez", "Hamilton", "Harper", "Hawkins", 
        "Hernandez", "Hughes", "Hunter", "Jackson", "Jenkins", "Jordan", "Kelly", 
        "Khan", "King", "Knight", "Lawrence", "Lewis", "Lopez", "Marshall", "Mason", 
        "Mendoza", "Miller", "Mitchell", "Morgan", "Morris", "Murphy", "Murray", 
        "Myers", "Nelson", "Newton", "O’Brien", "Oliver", "Palmer", "Patel", "Perez", 
        "Phillips", "Price", "Reed", "Reyes", "Richardson", "Robinson", "Rodriguez", 
        "Rogers", "Ross", "Russell", "Sanders", "Shaw", "Simpson", "Snyder", "Stephens", 
        "Stewart", "Sullivan", "Terry", "Torres", "Turner", "Vargas", "Vasquez", 
        "Wallace", "Ward", "Watson", "Weaver", "Webb", "Wells", "West", "Williams", 
        "Wilson", "Wood", "Yates", "Allen", "Bishop", "Blake", "Bradley", "Burgess", 
        "Burton", "Carter", "Cunningham", "Euwenn", "Davidson", "Douglas", "Doyle", 
        "Edward", "Ferguson", "Franklin", "Gilbert", "Gill", "Griffith", "Hart", 
        "Henderson", "Holland", "Hopkins", "Howard", "Jennings", "Johnston", "Joseph", 
        "Kelley", "Kennedy", "Lam", "Larson", "Lawson", "Leonard", "Little", "Long", 
        "Lowe", "Lyons", "Malone", "Marshallo", "Martin", "Matthews", "McCarthy", 
        "McDonald", "McGee", "McKinney", "Mejia", "Mills", "Montgomery", "Moorei", 
        "Morrison", "Neal", "Tonew", "Norris", "O’Connor", "Owens", "Palmers", 
        "Paterson", "Pena", "Perry", "Peters", "Powell", "Quinn", "Ramos", "Ray", 
        "Reid", "Reys", "Richards", "Rivera", "Romero", "Sampson", "Schneider", 
        "Shepherd", "Smith", "Spencer", "Steele", "Stephenson", "Stevenson", 
        "Sutton", "Swanson", "Tate", "Todd", "Tyler", "Valencia", "Vega", "Vinson", 
        "Wallace", "Walters", "Ward", "Weaver", "Webb", "Whitaker", "Wilkins", 
        "Williams", "Wright", "Yates",
        "Abbott", "Beck", "Carlson", "Chavez", "Decker", "Fleming", "Garner", "Harding", 
        "Ingram", "Lindsey", "Maddox", "Nash",

        "Abel", "Alvarez", "Baldwin", "Barlow", "Beasley", "Benson", "Blanchard", "Booth",
        "Bradford", "Browning", "Buckley", "Burns", "Carver", "Casey", "Chavez", "Chamberlain",
        "Clarkson", "Clay", "Clifford", "Conley", "Crawford", "Curtin", "Davenport", "Day",
        "Delaney", "Drake", "Dunne", "Durham", "Ellington", "Emery", "Farrell", "Fletcher",
        "Fowler", "Fraser", "Gallagher", "Gibbons", "Gilliam", "Glover", "Gordon", "Griffiths",
        "Hammond", "Hardin", "Harmon", "Hawkins", "Henderson", "Holt", "Hudson", "Hunt",
        "Jefferson", "Jensen", "Kane", "Keller", "Kent", "Kingston", "Knox", "Lamb",
        "Lane", "Lawson", "Lee", "Levine", "Lloyd", "Lynch", "Mack", "Mann",
        "Mason", "May", "McBride", "McLaughlin", "McMillan", "Monroe", "Morris", "Murphy",
        "Nolan", "Olsen", "Parker", "Peterson", "Phillips", "Preston", "Price", "Reid",
        "Reyes", "Robbins", "Roth", "Sampson", "Shaw", "Shepard", "Silva", "Singleton",
        "Stone", "Summers", "Tate", "Thomson", "Tucker", "Underwood", "Vaughn", "Watts",
        "Webster", "Wells", "Whitney", "Winters", "Wood", "Woods", "Ziegler", "Zimmerman",

        "Adams", "Alexander", "Alford", "Alvarez", "Armstrong", "Ashley", "Barker", "Barnes",
        "Barrett", "Barton", "Bauer", "Beasley", "Becker", "Bennett", "Benton", "Berg", "Bernstein",
        "Black", "Blair", "Blanton", "Bliss", "Boles", "Bolton", "Bordelon", "Bowen", "Bradford", 
        "Brandon", "Bray", "Brewer", "Bridges", "Briggs", "Britt", "Brooks", "Brownell", "Bryan", 
        "Burns", "Burt", "Butler", "Byers", "Calhoun", "Campbell", "Carson", "Chavez", "Clarkson", 
        "Clayton", "Clemons", "Clifford", "Collier", "Collins", "Cooke", "Cooley", "Craig", "Crawford", 
        "Cross", "Curtis", "Davis", "Dawson", "Day", "Decker", "Dennis", "Dixon", "Douglas", "Draper", 
        "Durham", "Dyer", "Eason", "Edwards", "Ellis", "Evans", "Farrell", "Fawcett", "Ferguson", "Fisher", 
        "Fitzgerald", "Flanagan", "Fleming", "Ford", "Foreman", "Freeman", "Gamble", "Garcia", "Gardner", 
        "Garrison", "Gibson", "Gilbert", "Glover", "Gonzalez", "Goodman", "Gordon", "Graham", "Grant", 
        "Graves", "Greer", "Green", "Griffin", "Gunter", "Hale", "Hall", "Hamilton", "Hammond", "Hansen", 
        "Harris", "Hart", "Hawkins", "Hayes", "Henderson", "Hickman", "Hill", "Hobbs", "Holmes", "Hopkins", 
        "Hughes", "Hunt", "Hunter", "Ingram", "Jackson", "James", "Jenkins", "Johnston", "Jones", "Jordan", 
        "Joseph", "Judd", "Kaiser", "Kelley", "Kennedy", "King", "Knight", "Koch", "Lane", "Lang", "Lawson", 
        "Leach", "Lee", "Leonard", "Lewis", "Little", "Lloyd", "Lynch", "Maddox", "Malone", "Mann", "Marshall", 
        "Martin", "Mason", "Matthews", "McCarthy", "McClure", "McDonald", "McGee", "McKinney", "Merritt", 
        "Mitchell", "Morrison", "Moses", "Myers", "Nash", "Nelson", "Newton", "Nixon", "Oliver", 
        "Osborne", "Parker", "Patterson", "Payne", "Peck", "Perry", "Peterson", "Phillips", "Pitts", "Pollard", 
        "Porter", "Price", "Quinn", "Reed", "Reese", "Reilly", "Reyes", "Richards", "Richardson", "Riley", 
        "Roberts", "Robertson", "Rodriguez", "Rollins", "Rose", "Ross", "Russell", "Ryan", "Sampson", "Sanders", 
        "Schmidt", "Schneider", "Scott", "Shaw", "Shepherd", "Simmons", "Simpson", "Sloan", "Smith", "Snyder", 
        "Spencer", "Steele", "Stephens", "Stewart", "Sullivan", "Swanson", "Taylor", "Thomas", "Thompson", 
        "Todd", "Towers", "Turner", "Vance", "Vargas", "Vaughn", "Vega", "Vincent", "Wade", "Walker", "Ward", 
        "Watson", "Webb", "Wells", "West", "Weston", "Wheeler", "White", "Wilkins", "Williams", "Wilson", 
        "Wood", "Yates", "Young", "Abel", "Albert", "Alford", "Anderson", "Anthony", "Archer", 
        "Austin", "Baca", "Baker", "Ballard", "Bandy", "Barlow", "Barton", "Bass", "Beck", "Becker", "Bellamy", 
        "Bennett", "Berry", "Blackwell", "Blanchard", "Blevins", "Bliss", "Browning", "Buchanan", "Burns", 
        "Byrne", "Callahan", "Carson", "Chambers", "Chapman", "Charles", "Chavez", "Christian", "Clark", "Clay", 
        "Clifford", "Coates", "Cole", "Collier", "Conner", "Cook", "Craig", "Curtis", "Dallas", "Davidson", 
        "Davenport", "Dawson", "Delgado", "Dennis", "Dixon", "Donaldson", "Doyle", "Douglas", "Drake", "Durham", 
        "Eckert", "Elliott", "Ellison", "Emerson", "Ennis", "Evans", "Ferguson", "Finley", "Fisher", "Fitzgerald", 
        "Fowler", "Franklin", "Frost", "Garcia", "Garrison", "Garvey", "Gilmore", "Gonzalez", "Gordon", "Green", 
        "Greer", "Griffith", "Grimes", "Guerrero", "Hamilton", "Hansen", "Hardin", "Harris", "Hartman", "Hayward", 
        "Holman", "Holland", "Hopkins", "Howard", "Hudson", "Hughes", "Hunt", "Hyman", "Irwin", "Jackson", "James", 
        "Jefferson", "Jenkins", "Jensen", "Johnson", "Jones", "Joseph", "Judd", "Kaiser", "Kennedy", "Kerr", 
        "Kelley", "King", "Lacy", "Larkin", "Lee", "Leonard", "Lewis", "Lloyd", "Lynch", "Malone", "Marin", "Martin", 
        "Mason", "Mayer", "McAllister", "McBride", "McClain", "McDonald", "McGee", "McKinney", "Miller", "Mitchell", 
        "Moore", "Morris", "Myers", "Nelson", "Newman", "O’Neill", "Oliver", "Ortega", "Owen", "Parker", "Patterson", 
        "Peck", "Perry", "Phillips", "Porter", "Powers", "Price", "Reed", "Reilly", "Reyes", "Roberts", "Robinson", 
        "Rogers", "Rollins", "Russell", "Ryan", "Sampson", "Sanchez", "Schmidt", "Shaw", "Shepard", "Sloan", 
        "Smithson", "Snyder", "Sparks", "Stewart", "Stone", "Sutton", "Swanson", "Taylor", "Terry", "Thompson", 
        "Thorne", "Todd", "Tucker", "Turner", "Vaughn", "Vega", "Vincent", "Walker", "Ward", "Watson", "Wells", 
        "Wheeler", "White", "Williams", "Wilson", "Wright", "Wyatt", "Yates", "Zapata", "Zimmerman",
        
        "Abbott", "Ackerman", "Akins", "Alford", "Alvarez", "Amos", "Andersen", "Angell", "Ashley", 
        "Atkins", "Austin", "Babcock", "Baker", "Baldwin", "Ball", "Barber", "Barnes", "Barr", "Bates", 
        "Beach", "Beasley", "Bellamy", "Benitez", "Benton", "Berman", "Bettencourt", "Bishop", "Blanchard", 
        "Bliss", "Bond", "Booker", "Boren", "Bourgeois", "Bowman", "Boyce", "Bradley", "Brady", "Brennan", 
        "Briggs", "Brinton", "Broderick", "Browning", "Brunson", "Buchanan", "Buckner", "Burk", "Burns", 
        "Burton", "Butler", "Byers", "Callahan", "Calhoun", "Campbell", "Carson", "Castro", "Chapman", 
        "Charles", "Chavez", "Cheng", "Choi", "Christensen", "Clarkson", "Clifton", "Cole", "Collier", 
        "Colon", "Compton", "Conner", "Cook", "Crawford", "Cross", "Curtis", "Curtis", "Dalton", "Davidson", 
        "Delgado", "Dennis", "Devin", "Diaz", "Dillard", "Douglas", "Doyle", "Duncan", "Dunlap", "Durham", 
        "Eaton", "Edwards", "Elliott", "Ellis", "Emerson", "Evans", "Farley", "Ferguson", "Fields", "Fitzgerald", 
        "Floyd", "Ford", "Freeman", "Gamble", "Garcia", "Garrison", "Gibson", "Gilbert", "Gill", "Glover", 
        "Gonzalez", "Grant", "Green", "Griffin", "Guthrie", "Hale", "Hall", "Hamilton", "Hancock", "Harding", 
        "Harper", "Harris", "Harrison", "Hartman", "Hawkins", "Hayes", "Henderson", "Hicks", "Holland", 
        "Holmes", "Howard", "Howell", "Hudson", "Hughes", "Hunt", "Jackson", "James", "Jenkins", "Jennings", 
        "Johnson", "Jones", "Jordan", "Kaiser", "Kelley", "Kennedy", "Kerr", "Khan", "King", "Klein", 
        "Knight", "Lacey", "Lamb", "Lane", "Lawson", "Leonard", "Lewis", "Lindsay", "Little", "Long", 
        "Lopez", "Lowe", "Lynch", "Maddox", "Malone", "Manning", "Marshall", "Martin", "Mason", "Matthews", 
        "Maxwell", "Mayer", "McAllister", "McCarty", "McClain", "McDonald", "McGee", "McGrath", "McKinney", 
        "McLean", "Miller", "Mills", "Mitchell", "Moore", "Morris", "Murphy", "Murray", "Myers", "Nelson", 
        "Newton", "Nichols", "O'Connor", "O'Neill", "Olson", "Orr", "Palmer", "Parker", "Patel", "Patterson", 
        "Peck", "Perez", "Perry", "Peters", "Phillips", "Porter", "Powell", "Powers", "Quinn", "Ramos", 
        "Ray", "Reed", "Reese", "Reid", "Reynolds", "Rios", "Roberts", "Robinson", "Rodriguez", "Rogers", 
        "Rollins", "Ross", "Rowe", "Rudd", "Sampson", "Sanchez", "Schmidt", "Schneider", "Scott", "Sellers", 
        "Sharp", "Shepherd", "Simpson", "Simmons", "Sloan", "Smith", "Snyder", "Spencer", "Spivey", "Stewart", 
        "Stone", "Swanson", "Tate", "Taylor", "Thomas", "Thompson", "Tiffany", "Turner", "Vance", "Vargas", 
        "Vasquez", "Vega", "Wallace", "Walsh", "Ward", "Warren", "Watson", "Weaver", "Webb", "Wells", 
        "West", "Whitaker", "White", "Wilkins", "Williams", "Wilson", "Woods", "Yates", "Zimmerman", 
        "Zuniga", "Abbot", "Allen", "Anderson", "Arnold", "Avery", "Baldwin", "Barber", "Barnes", "Barrett", 
        "Beasley", "Bell", "Benson", "Bergman", "Berman", "Bernstein", "Blake", "Blanchard", "Bliss", "Bond", 
        "Booker", "Boren", "Bourgeois", "Bowman", "Bradley", "Brady", "Bray", "Brewer", "Briggs", "Brock", 
        "Brooks", "Brown", "Bryant", "Buchanan", "Burns", "Burton", "Byers", "Calhoun", "Carson", "Carter", 
        "Chapman", "Chen", "Christian", "Clarkson", "Clifton", "Cline", "Collier", "Cook", "Cooper", "Craig", 
        "Cross", "Curtis", "Dalton", "Davidson", "Diaz", "Douglas", "Doyle", "Duncan", "Dunlap", "Durham", 
        "Eaton", "Edwards", "Elliott", "Ellis", "Fletcher", "Ford", "Freeman", "Gamble", "Garcia", "Garner", 
        "Gibson", "Gilbert", "Glover", "Gonzalez", "Grant", "Greer", "Griffin", "Hale", "Hall", "Hamilton", 
        "Hancock", "Harding", "Harmon", "Harper", "Harris", "Hayes", "Henderson", "Hicks", "Holland", "Holmes", 
        "Howard", "Hughes", "Hunter", "Hunt", "Jackson", "James", "Jenkins", "Johnson", "Jones", "Jordan", 
        "Kaiser", "Kelley", "Kennedy", "Kerr", "Khan", "King", "Klein", "Knight", "Lacey", "Lamb", 
        "Lane", "Larson", "Laws", "Lawson", "Leonard", "Lewis", "Lloyd", "Lowe", "Lyons", "Malone", 
        "Marshall", "Martin", "Mason", "Matthews", "McAllister", "McClain", "McDonald", "McGee", 
        "McKinney", "Miller", "Mitchell", "Morris", "Murphy", "Myers", "Nelson", "Newton", "O'Connor", 
        "Oliver", "Parker", "Patterson", "Peck", "Perez", "Perry", "Peterson", "Phillips", "Porter", 
        "Powell", "Pritchard", "Reed", "Reid", "Richards", "Roberts", "Robertson", "Rodriguez", "Rogers", 
        "Rollins", "Ross", "Rowe", "Sampson", "Sanchez", "Schneider", "Scott", "Sellers", "Simmons", 
        "Sloan", "Smith", "Snyder", "Spencer", "Stewart", "Stone", "Swanson", "Tate", "Taylor", "Thomas", 
        "Thompson", "Turner", "Vaughn", "Vega", "Wallace", "Ward", "Watson", "Weaver", "Webb", "Wells",

        "Adams", "Allen", "Anderson", "Baker", "Baldwin", "Ball", "Barnes", "Barton", "Becker", "Bell", 
        "Benjamin", "Benson", "Bernard", "Berry", "Bishop", "Black", "Blake", "Blanchard", "Blevins", "Bliss", 
        "Booth", "Bowers", "Boyd", "Bradshaw", "Brewer", "Brooks", "Brown", "Bryan", "Buckley", "Burch", 
        "Burgess", "Burnett", "Burton", "Butler", "Byers", "Cameron", "Campbell", "Carlson", "Carter", "Chapman", 
        "Charles", "Clark", "Clayton", "Cleveland", "Clifford", "Cole", "Collier", "Combs", "Cook", "Cooper", 
        "Corbett", "Craig", "Curtis", "Davis", "Dawson", "Day", "Delgado", "Diaz", "Dillard", "Dixon", 
        "Douglas", "Doyle", "Drake", "Dunn", "Durham", "Edwards", "Ellis", "Ferguson", "Fields", "Fischer", 
        "Fitzgerald", "Fleming", "Flores", "Ford", "Franklin", "Freeman", "Gage", "Garcia", "Garrison", "Gibson", 
        "Gilbert", "Gill", "Glover", "Goldstein", "Gonzalez", "Goodman", "Grant", "Greene", "Griffith", "Guthrie", 
        "Hall", "Hamilton", "Hancock", "Hardin", "Harper", "Harris", "Hart", "Hawkins", "Hayden", "Henderson", 
        "Hernandez", "Hicks", "Hill", "Hines", "Holland", "Holmes", "Howard", "Hudson", "Hunter", "Jackson", 
        "James", "Jenkins", "Johnson", "Jones", "Jordan", "Joseph", "Kelly", "Kennedy", "Kerr", "Kim", 
        "King", "Klein", "Knight", "Lambert", "Lane", "Larsen", "Lawson", "Lee", "Lewis", "Lindsey", 
        "Little", "Long", "Lopez", "Lowe", "Lynch", "Malone", "Marshall", "Martin", "Mason", "Mathews", 
        "Maxwell", "McAllister", "McCarthy", "McClain", "McDonald", "McGee", "McKenzie", "McKinney", "Miller", 
        "Mills", "Mitchell", "Moore", "Morris", "Murphy", "Myers", "Nelson", "Nichols", "Norris", "O'Connor", 
        "O'Neill", "Oliver", "Parker", "Patel", "Peck", "Perez", "Perry", "Peters", "Phillips", "Pierce", 
        "Powell", "Powers", "Price", "Quinn", "Reed", "Reid", "Richards", "Richardson", "Riley", "Roberts", 
        "Robinson", "Rodriguez", "Rogers", "Rollins", "Ross", "Roth", "Russell", "Salazar", "Sampson", "Sanders", 
        "Scott", "Shaw", "Shepard", "Shepherd", "Simpson", "Simmons", "Sloan", "Smith", "Snyder", "Spencer", 
        "Stewart", "Stone", "Swanson", "Taylor", "Thompson", "Tucker", "Turner", "Vance", "Vargas", "Vega", 
        "Vinson", "Wade", "Wallace", "Ward", "Watson", "Webb", "Wells", "West", "Wheeler", "Whitaker", 
        "White", "Wilkins", "Williams", "Wilson", "Wood", "Yates", "Zimmerman", "Adkins", "Aguirre", "Alford", 
        "Alvarado", "Angelo", "Archer", "Armstrong", "Austin", "Bailey", "Baker", "Ballard", "Barrett", "Barrios", 
        "Beasley", "Benson", "Berg", "Berman", "Bernstein", "Blackwell", "Blair", "Bliss", "Bose", "Brady", 
        "Bridges", "Brock", "Brooks", "Brown", "Bruce", "Bryant", "Buchanan", "Burch", "Burnett", "Burns", 
        "Byers", "Caldwell", "Campbell", "Carlson", "Carson", "Chavez", "Cicero", "Clancy", "Clark", "Clifford", 
        "Collier", "Conner", "Cook", "Copeland", "Craig", "Curtis", "Dawson", "Delgado", "Diaz", "Dickson", 
        "Dorsey", "Douglas", "Doyle", "Duncan", "Durham", "Ellis", "Fisher", "Fleming", "Freeman", "Frost", 
        "Gaines", "Garcia", "Garner", "Gibson", "Gilbert", "Glover", "Gonzalez", "Grant", "Green", "Griffin", 
        "Gross", "Hall", "Hamilton", "Harmon", "Harrison", "Hart", "Hawkins", "Hayes", "Henderson", "Hernandez", 
        "Holbrook", "Holloway", "Howard", "Hudson", "Hughes", "Hunt", "Ingram", "Jackson", "James", "Jenkins", 
        "Jones", "Jordan", "Kaiser", "Kelly", "Kennedy", "Kerr", "Kim", "King", "Knight", "Landry", "Lane", 
        "Lawson", "Lindsey", "Lopez", "Lowe", "Lynch", "Maddox", "Malone", "Marsh", "Martin", "Mathews", 
        "McCarthy", "McClain", "McDonald", "McGee", "McGrath", "McKinney", "Miller", "Mitchell", "Moore", 
        "Morris", "Murphy", "Myers", "Nelson", "Nichols", "O'Connor", "O'Neill", "Olson", "Parker", "Patel", 
        "Perez", "Perry", "Peters", "Phillips", "Price", "Powers", "Quinn", "Reed", "Reid", "Reynolds", 
        "Roberts", "Robinson", "Rodriguez", "Rogers", "Rollins", "Sampson", "Sanders", "Scott", "Sellers", 
        "Simmons", "Sloan", "Smith", "Snyder", "Spencer", "Stewart", "Stone", "Swanson", "Taylor", "Thomas", 
        "Thompson", "Turner", "Vance", "Vargas", "Vega", "Vinson", "Wallace", "Walters", "Ward", "Weaver", 
        "Webb", "Whitaker", "Williams", "Wright", "Young",

        "Abadiano", "Alipio", "Arroyo", "Asuncion", "Balanza", "Bautista", "Bermudez", "Bicaldo", "Caballero", "Cabrera",
        "Cabugao", "Cajigas", "Calixto", "Calvo", "Canda", "Cano", "Carreon", "Casion", "Catalan", "Castillo",
        "Catipon", "Cayabyab", "Cayton", "Chavez", "Chua", "Claudio", "Dalisay", "Datu", "Dela Cruz", "Delos Reyes",
        "Dimaculangan", "Dizon", "Divina", "Dumlao", "Duran", "Escobar", "Espina", "Esquivel", "Eufemio", "Fajardo",
        "Ferrer", "Flores", "Fontanilla", "Fortuna", "Francisco", "Gacusan", "Galang", "Gamboa", "Ganao", "Garcia",
        "Gatchalian", "Gimeno", "Gonzales", "Gonzalez", "Guerrero", "Guiterrez", "Gutierrez", "Hernando", "Hernandez",
        "Javier", "Jimenez", "Juan", "Jumalon", "Labrador", "Lacson", "Lama", "Lanuza", "Lao", "Lao", "Lapos",
        "Lazaro", "Leoncio", "Llamas", "Llorente", "Lutero", "Magno", "Magtoto", "Manalo", "Manlapig", "Manuel",
        "Marasigan", "Mariano", "Maringo", "Marmol", "Mendoza", "Mercado", "Morales", "Moreno", "Navarro", "Ocampo",
        "Ortega", "Pablito", "Pagdanganan", "Palanan", "Pascual", "Patawaran", "Patag", "Pangilinan", "Paredes", "Paraiso",
        "Pascua", "Peralta", "Pilar", "Pineda", "Pio", "Policarpio", "Puno", "Quijano", "Ramos", "Reyes", "Rico",
        "Rodriguez", "Romero", "Santos", "Sarmiento", "Salazar", "Salvador", "San Diego", "Santiago", "Santos",
        "Silva", "Sinajon", "Solano", "Sumalinog", "Tabora", "Tan", "Tejada", "Tee", "Teodoro", "Tendencia",
        "Tiu", "Torres", "Tumbaga", "Tumulak", "Ubaldo", "Ubanan", "Valerio", "Vega", "Vergara", "Villacorta",
        "Villanueva", "Villar", "Villaruel", "Villasanta", "Vinluan", "Yap", "Yulfo",

        "Abaya", "Adriano", "Agbayani", "Alcantara", "Alcove", "Alejo", "Alon", "Alvarado", "Aniceto", "Arceo",
        "Atienza", "Balisacan", "Baril", "Batac", "Bautista", "Binghay", "Bulaon", "Cabangon", "Cabeguin", "Calamba",
        "Canete", "Casimiro", "Castro", "Cordero", "Cuenca", "Cuya", "Dacumos", "Dalangin", "Danao", "Dela Torre",
        "Delmendo", "Demeterio", "Dizon", "Diaz", "Dizon", "Galacgac", "Gapan", "Garces", "Garrido", "Gaviola",
        "Gloria", "Hernandez", "Ilagan", "Jalandoni", "Jurado", "Kasilag", "Lacap", "Lacuna", "Ladiera", "Lagmay",
        "Legarda", "Lirio", "Lobaton", "Mabalay", "Mabulay", "Malabanan", "Manlapig", "Manuel", "Mapagsanghan",
        "Marasigan", "Maravilla", "Mendieta", "Mendez", "Mercado", "Mijares", "Morales", "Moreno", "Nieves", 
        "Oba", "Ong", "Osias", "Pablo", "Pangilinan", "Paraiso", "Parin", "Pascua", "Pelegrino", "Peralta", 
        "Perez", "Pineda", "Policarpio", "Quito", "Ramos", "Reta", "Salazar", "Salvador", "Sanchez", "Sanglay", 
        "Serafica", "Sison", "Tabora", "Tadena", "Talamayan", "Tanyag", "Tayag", "Tejero", "Tiu", "Tolentino", 
        "Torres", "Tumulak", "Valdez", "Valera", "Velasco", "Villarosa", "Villoria", "Zamora", "Zaragoza",

        "Abad", "Aguilar", "Alano", "Alcantara", "Alona", "Antiporda", "Aponte", "Arambulo", "Arce", "Bacani",
        "Bagabaldo", "Banez", "Bautista", "Blanca", "Bohol", "Bulan", "Caguioa", "Calalang", "Calipay", "Canlas",
        "Cardenas", "Carillo", "Chavez", "Chiong", "Ciriaco", "Claravall", "Comia", "Completos", "Cordero",
        "Cruz", "Dacanay", "Dantes", "Dayanghirang", "De la Peña", "De Guzman", "Delos Santos", "Dizon", "Durano",
        "Escalante", "Esquivel", "Fajardo", "Flores", "Fontanilla", "Garcia", "Geronimo", "Gonzaga", "Guerra",
        "Guerrero", "Ibañez", "Jeronimo", "Lacson", "Lansi", "Lao", "Laoag", "Laoacan", "Lazo", "Liu", "Lopez",
        "Luna", "Mabanta", "Mendoza", "Montano", "Mora", "Morales", "Moreno", "Navarro", "Ocampo", "Oliva",
        "Ordinario", "Pajarillo", "Pante", "Parreno", "Pascual", "Ramos", "Reyes", "Rico", "Rivilla", "Rodriguez",
        "Salazar", "Santiago", "Sarmiento", "Simbol", "Sinamban", "Sison", "Taboada", "Tagle", "Tantuico", "Tia",
        "Yap", "Zobel",

        "Abarca", "Abubakar", "Acosta", "Adlawan", "Agbayani", "Alfonso", "Almeda", "Alzate", "Amparo", "Ancheta",
        "Ang", "Antonio", "Arrieta", "Astorga", "Atienza", "Bacani", "Badajoz", "Balingit", "Baluyot", "Bañez",
        "Barrameda", "Bautista", "Bodet", "Boquiren", "Buan", "Caballes", "Cabilao", "Cabral", "Caguioa", "Calderon",
        "Calzo", "Capili", "Caseres", "Castro", "Catipon", "Celis", "Ching", "Dahilig", "Dapat", "De Guzman",
        "Del Mundo", "Del Rosario", "Dematera", "Dino", "Dizon", "Escueta", "Estrella", "Galang", "Garcillano",
        "Gatbonton", "Gaya", "Golez", "Gonzales", "Gonzalo", "Gumabon", "Hidalgo", "Ilagan", "Inocencio", "Ira",
        "Jamorabon", "Javier", "Ladaga", "Ladiao", "Lagman", "Lao", "Lariosa", "Lariosa", "Lazo", "Ledesma",
        "Libanan", "Lobregat", "Macaraeg", "Magat", "Magpantay", "Magsino", "Manalo", "Manlapig", "Mansilla"
    ];
  
  return lastNames.map(name => `${name.toLowerCase()}@gmail.com`);
}

const generateEmailsForHostProfile = () => {
  const email = [
   "hazel.delito@yahoo.com", 
   "amicabalmores@gmail.com", 
   "ltaguibao@yahoo.com", 
   "dvydgzmn@gmail.com", 
   "addisonreyesandal@gmail.com", 
   "Jennerieespinosa@gmail.com", 
   "Legaspikrizanicole@gmail.com", 
   "Omaymahmateo@gmail.com", 
   "jumalonerika@gmail.com", 
   "kyzerzyryll@gmail.com", 
   "alexdcmedina0712@gmail.com", 
   "timothybaylon0@gmail.com", 
   "deguzmanmart4@gmail.com", 
   "tycoons88g.taylor@gmail.com", 
   "Jisellebonifacio1102@gmail.com", 
   "jjavierriel@gmail.com", 
   "charmaysoriano92@gmail.com", 
   "gmongcopa@gmail.com", 
   "Charmainejoym1@icloud.com", 
  ]
  return email;
}

module.exports = {
  generateEmails,
  generateEmailsForHostProfile
};